### ISSUE TITLE
error posting

### ISSUE THREAD

**Issue by zodman** [jyr/opentumblr#1]
zodman@cosmogirl opentumblr]$ python opentumblr/opentumblr-client.py 
Te haz logueado
Traceback (most recent call last):
  File "/home/zodman/devel/opentumblr/opentumblr/text.py", line 119, in OnCreatePost
    self.post = self.api.write_regular(self.title, self.body)
  File "/home/zodman/devel/opentumblr/opentumblr/tumblr.py", line 140, in write_regular
    return self._write(args)
  File "/home/zodman/devel/opentumblr/opentumblr/tumblr.py", line 268, in _write
    raise TumblrError("Error writing post")
tumblr.TumblrError: Error writing post

**Comment by jyr** [comment]
listo, gracias
